export const data = [
  {
    name: "Bohemian Rhapsody",
    released: "1975",
    writer: "Freddie Mercury",
    song: "Single by Queen",
    id: "3434efrd",
    url: "https://upload.wikimedia.org/wikipedia/en/9/9f/Bohemian_Rhapsody.png",
    class: "active",
  },
  {
    name: "Hotel California",
    released: "1977",
    writer: "Don Felder.Don Henley.Glenn Frey",
    song: "Single by Eagles",
    id: "343dgf",
    url: "https://upload.wikimedia.org/wikipedia/en/4/49/Hotelcalifornia.jpg",
    class: "",
  },
  {
    name: "Billie Jean",
    released: "1983",
    writer: "Michael Jackson",
    song: "Michael Jackson",
    id: "yty133t",
    url: "https://upload.wikimedia.org/wikipedia/en/thumb/5/55/Michael_Jackson_-_Thriller.png/220px-Michael_Jackson_-_Thriller.png",
    class: "",
  },
];
